[project]
name = "csck502"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deap>=1.4.3",
    "tabulate>=0.9.0",
    "tqdm>=4.67.1",
    "wordfreq>=3.1.1",
]
